-- Adana Nakliyat Rehberi — mevcut veriler (MySQL -> PostgreSQL)
-- 01-sema.sql calistirildiktan SONRA bir kez calistir.

insert into iller (id, ad, slug, baslik, aciklama, ozet, metin, sira, aktif) values
  (1, 'Adana', 'adana', 'Adana Evden Eve Nakliyat Firmaları', 'Adana evden eve nakliyat firmaları rehberi. İlçe ilçe firma listesi, telefon, adres ve puanlar. Ücretsiz teklif alın.', 'Adana merkez ve ilçelerde çalışan nakliyat firmalarını adres, telefon ve puanlarıyla listeledik.', '<p>Adana ev taşıma firmaları arasında seçim yaparken bakılması gereken ilk şey, firmanın taşıma yaptığı bölgeyi gerçekten tanıyıp tanımadığıdır. Seyhan''ın dar sokakları, Çukurova''nın yüksek katlı siteleri ve Yüreğir''in geniş bulvarları birbirinden farklı ekipman ister.</p><h3>Fiyatı belirleyen etkenler</h3><ul><li>Evin metrekaresi ve oda sayısı</li><li>Çıkış ve varış katı, binada asansör olup olmadığı</li><li>Dış cephe asansörü gerekip gerekmediği</li><li>Mesafe: şehir içi mi, şehirler arası mı</li><li>Paketleme, montaj-demontaj ve sigorta gibi ek hizmetler</li></ul><h3>Teklif alırken dikkat edin</h3><p>Adana nakliye firmaları çoğunlukla telefonda kaba bir fiyat verir, ancak sağlıklı fiyat için eve gelinip ekspertiz yapılması gerekir. En az üç firmadan teklif alın, fiyatın neyi kapsadığını yazılı isteyin.</p><h3>Sigorta ve sözleşme</h3><p>Adana ev taşıma firmaları arasında taşıma sigortası sunanlar bulunur. Kıymetli eşyanız varsa sigortayı mutlaka talep edin ve sözleşmede eşya listesinin yer aldığından emin olun.</p>', 1, true)
on conflict (id) do nothing;

insert into ilceler (id, il_id, ad, slug, baslik, aciklama, ozet, metin, sira, aktif) values
  (1, 1, 'Seyhan', 'seyhan', 'Seyhan Evden Eve Nakliyat Firmaları', 'Adana Seyhan evden eve nakliyat firmaları listesi. Telefon, adres ve puanlarıyla Seyhan nakliyat firmaları.', 'Seyhan Adana''nın en yoğun ilçesi ve nakliyat firmalarının büyük bölümü burada. Gürselpaşa, Tellidere, Pınar ve Fatih mahalleleri firma ofislerinin toplandığı bölgeler.', '<p>Seyhan''da taşınırken en sık karşılaşılan sorun sokak darlığı ve park yeri. Reşatbey, Ziyapaşa ve Çınarlı gibi merkez mahallelerde kamyonun kapının önüne yanaşması her zaman mümkün olmuyor; bu yüzden Seyhan''da çalışan Adana taşıma şirketleri çoğunlukla dış cephe asansörüyle iş yapar. Eski yapı stoğunun yoğun olduğu Kurtuluş ve Dağlıoğlu tarafında merdiven boşlukları dar olduğu için mobilyanın demonte edilmesi gerekir. Taşınma tarihini hafta içi seçmeniz hem trafiği hem de fiyatı olumlu etkiler.</p>', 1, true),
  (2, 1, 'Çukurova', 'cukurova', 'Çukurova Evden Eve Nakliyat Firmaları', 'Adana Çukurova evden eve nakliyat firmaları listesi. Telefon, adres ve puanlarıyla Çukurova nakliyat firmaları.', 'Çukurova, Adana''nın yeni ve yüksek katlı site bölgesi. Huzurevleri, Toros, Yüzüncüyıl ve Kurttepe''de taşınmalar genellikle asansörlü ve rezidans kurallarına tabi.', '<p>Çukurova''daki sitelerde taşınma için önceden yönetimden izin alınması, çoğu zaman da belirli saat aralığında çalışılması isteniyor. Adana nakliye firmaları bu bölgede işe başlamadan önce site yönetimiyle görüşür ve asansör kullanımı için koruyucu örtü serer. 10. kat üzerindeki dairelerde dış cephe asansörünün boyu kritik; teklif alırken kaçıncı katta olduğunuzu mutlaka belirtin. Huzurevleri ve Yüzüncüyıl çevresinde asansör kiralama hizmeti veren firmalar da bulunuyor.</p>', 2, true),
  (3, 1, 'Yüreğir', 'yuregir', 'Yüreğir Evden Eve Nakliyat Firmaları', 'Adana Yüreğir evden eve nakliyat firmaları listesi. Telefon, adres ve puanlarıyla Yüreğir nakliyat firmaları.', 'Yüreğir''de sokaklar Seyhan''a göre daha geniş, bu da kamyonun kapı önüne yanaşmasını kolaylaştırıyor. Kışla, Atakent ve Sinanpaşa çevresi en çok taşınma yapılan bölgeler.', '<p>Yüreğir''de müstakil ve az katlı yapı oranı yüksek olduğu için taşımalar genellikle asansörsüz yapılabiliyor; bu da maliyeti düşürüyor. Ancak yeni yapılan sitelerde durum değişiyor, bu binalarda asansörlü taşıma tercih ediliyor. Yüreğir''den Seyhan veya Çukurova''ya taşınacaksanız köprü trafiği nedeniyle sabah erken saatlerde başlanmasını isteyin. Bölgede ofisi bulunan Adana ev taşıma firmaları sayısı merkez ilçelere göre daha az, bu yüzden randevuyu erken almanız iyi olur.</p>', 3, true),
  (4, 1, 'Sarıçam', 'saricam', 'Sarıçam Evden Eve Nakliyat Firmaları', 'Adana Sarıçam evden eve nakliyat firmaları listesi. Telefon, adres ve puanlarıyla Sarıçam nakliyat firmaları.', 'Sarıçam son yıllarda hızla büyüyen bir ilçe. Ertuğrulgazi, Şahintepe ve Mehmet Akif Ersoy mahallelerinde yeni konut projeleri nedeniyle taşınma trafiği yoğun.', '<p>Sarıçam''daki TOKİ ve yeni site bölgelerinde bloklar arası mesafe uzun olabiliyor; kamyonun bloğa yanaşamadığı durumlarda ek taşıma bedeli çıkabiliyor. Teklif alırken aracın kapıya kadar girip giremeyeceğini firmaya sorun. Merkeze uzaklık nedeniyle Seyhan merkezli firmalar Sarıçam işlerine yol farkı ekleyebiliyor, bu yüzden bölgede ofisi olan Adana nakliye firmalarından da teklif almanız fiyat avantajı sağlar.</p>', 4, true),
  (5, 1, 'Ceyhan', 'ceyhan', 'Ceyhan Evden Eve Nakliyat Firmaları', 'Adana Ceyhan evden eve nakliyat firmaları listesi. Telefon, adres ve puanlarıyla Ceyhan nakliyat firmaları.', 'Ceyhan, Adana merkeze 45 km uzaklıkta kendi nakliyat firmalarına sahip bir ilçe. Namık Kemal, Burhaniye ve Atatürk mahalleleri firma ofislerinin bulunduğu bölgeler.', '<p>Ceyhan''da hem ilçe içi hem de Adana merkeze taşınma talebi yoğun. Merkeze taşınacaksanız yol farkının fiyata dahil olup olmadığını baştan netleştirin, çünkü bazı firmalar bunu ayrı kalem olarak ekliyor. Ceyhan''daki Adana taşıma şirketlerinin bir kısmı aynı zamanda vinç ve lojistik hizmeti de veriyor; ağır makine veya iş yeri taşımanız varsa bu firmalar daha uygun oluyor. İlçedeki firma sayısı sınırlı olduğu için özellikle ay başı ve hafta sonu için randevuyu en az bir hafta önceden alın.</p>', 5, true),
  (6, 1, 'Kozan', 'kozan', 'Kozan Evden Eve Nakliyat Firmaları', 'Adana Kozan evden eve nakliyat firmaları listesi. Telefon, adres ve puanlarıyla Kozan nakliyat firmaları.', 'Kozan, Adana''nın kuzeyinde 70 km mesafede. Tufanpaşa, Türkeli ve Şevkiye mahallelerinde faaliyet gösteren yerleşik nakliyat firmaları var.', '<p>Kozan''dan Adana merkeze veya başka bir ile taşınmalarda mesafe fiyatın en belirleyici kalemi. Merkeze taşınıyorsanız hem Kozan''daki firmalardan hem de Seyhan merkezli firmalardan teklif alıp karşılaştırın; bazen merkez firmalarının dönüş yükü olduğu için fiyatı daha uygun çıkabiliyor. Kozan''ın eski mahallelerinde sokaklar dar ve eğimli, bu yüzden büyük kamyon yerine daha küçük araçla iki sefer yapılması gerekebilir. Adana ev taşıma firmaları arasında bu bölgeyi tanıyan biriyle çalışmak zaman kazandırır.</p>', 6, true),
  (7, 1, 'Karaisalı', 'karaisali', 'Karaisalı Evden Eve Nakliyat Firmaları', 'Adana Karaisalı evden eve nakliyat firmaları listesi. Telefon, adres ve puanlarıyla Karaisalı nakliyat firmaları.', 'Karaisalı, Toroslar''ın eteğinde yer alan bir ilçe. Bölgede lojistik ve şehirler arası taşıma ağırlıklı hizmet veriliyor.', '<p>Karaisalı''da yerleşik evden eve nakliyat firması sayısı çok az; taşınmaların büyük bölümü Adana merkezli firmalar tarafından yapılıyor. Merkezden gelen firmalar yol farkı uyguladığı için fiyat merkez içi taşımaya göre biraz daha yüksek oluyor. Dağlık kesimlere taşınacaksanız yol durumunu firmaya önceden bildirin, araç seçimi buna göre yapılır. Bu sayfada listelenen firmanın yanı sıra Seyhan sayfasındaki Adana nakliye firmalarından da teklif alabilirsiniz.</p>', 7, true)
on conflict (id) do nothing;

insert into kategoriler (id, ad, slug, baslik, aciklama, ozet, metin, sira, aktif) values
  (1, 'Evden Eve Nakliyat', 'evden-eve-nakliyat', 'Adana Evden Eve Nakliyat Firmaları', 'Adana evden eve nakliyat yapan firmalar. Telefon, adres ve ücretsiz teklif.', 'Şehir içi ev taşıma hizmeti veren firmalar.', NULL, 1, true),
  (2, 'Asansörlü Taşımacılık', 'asansorlu-tasimacilik', 'Adana Asansörlü Taşımacılık Firmaları', 'Adana asansörlü taşımacılık yapan firmalar. Telefon, adres ve ücretsiz teklif.', 'Dış cephe asansörüyle çalışan firmalar.', NULL, 2, true),
  (3, 'Şehirler Arası Nakliyat', 'sehirler-arasi-nakliyat', 'Adana Şehirler Arası Nakliyat Firmaları', 'Adana şehirler arası nakliyat yapan firmalar. Telefon, adres ve ücretsiz teklif.', 'İl dışına taşıma yapan firmalar.', NULL, 3, true),
  (4, 'Şehir İçi Taşıma', 'sehir-ici-tasima', 'Adana Şehir İçi Taşıma Firmaları', 'Adana şehir i̇çi taşıma yapan firmalar. Telefon, adres ve ücretsiz teklif.', 'Aynı şehir içinde kısa mesafe taşıma.', NULL, 4, true),
  (5, 'Eşya Depolama', 'esya-depolama', 'Adana Eşya Depolama Firmaları', 'Adana eşya depolama yapan firmalar. Telefon, adres ve ücretsiz teklif.', 'Eşyanızı depoda saklayan firmalar.', NULL, 5, true),
  (6, 'Parça Eşya Taşıma', 'parca-esya-tasima', 'Adana Parça Eşya Taşıma Firmaları', 'Adana parça eşya taşıma yapan firmalar. Telefon, adres ve ücretsiz teklif.', 'Tek parça veya az eşya gönderimi.', NULL, 6, true),
  (7, 'Asansör Kiralama', 'asansor-kiralama', 'Adana Asansör Kiralama Firmaları', 'Adana asansör kiralama yapan firmalar. Telefon, adres ve ücretsiz teklif.', 'Dış cephe asansörü kiralayan firmalar.', NULL, 7, true),
  (8, 'Uluslararası Nakliyat', 'uluslararasi-nakliyat', 'Adana Uluslararası Nakliyat Firmaları', 'Adana uluslararası nakliyat yapan firmalar. Telefon, adres ve ücretsiz teklif.', 'Yurt dışına taşıma yapan firmalar.', NULL, 8, true),
  (9, 'Lojistik', 'lojistik', 'Adana Lojistik Firmaları', 'Adana lojistik yapan firmalar. Telefon, adres ve ücretsiz teklif.', 'Yük ve lojistik hizmeti veren firmalar.', NULL, 9, true),
  (10, 'Vinç Hizmeti', 'vinc-hizmeti', 'Adana Vinç Hizmeti Firmaları', 'Adana vinç hizmeti yapan firmalar. Telefon, adres ve ücretsiz teklif.', 'Vinçli taşıma ve yük kaldırma.', NULL, 10, true),
  (11, 'Ofis Taşıma', 'ofis-tasima', 'Adana Ofis Taşıma Firmaları', 'Adana ofis taşıma yapan firmalar. Telefon, adres ve ücretsiz teklif.', 'İşyeri ve ofis taşıma hizmeti.', NULL, 11, true)
on conflict (id) do nothing;

insert into firmalar (id, il_id, ilce_id, ad, slug, mahalle, adres, tel, tel2, eposta, web, place_id, harita_link, enlem, boylam, aciklama, g_puan, g_puan_n, merkez, one_cikan, sira, aktif) values
  (1, 1, 1, 'Adana Çözüm Evden Eve Nakliyat', 'adana-cozum-evden-eve-nakliyat', 'Reşatbey', 'Reşatbey Mah. Türkkuşu Cd. No:76/D', '0539 328 48 01', NULL, NULL, NULL, 'ChIJJduYyH6JKBURZlKn5mn4Lho', 'https://www.google.com/maps/place/?q=place_id:ChIJJduYyH6JKBURZlKn5mn4Lho', NULL, NULL, 'Adana Çözüm Evden Eve Nakliyat, Adana Seyhan ilçesi Reşatbey mahallesinde faaliyet gösteriyor. Evden Eve, Şehirler Arası hizmetleri veriyor.', 5.0, 1, true, false, 1, true),
  (2, 1, 1, 'Şahin Ekspres Evden Eve Nakliyat ve Taşımacılık', 'sahin-ekspres-evden-eve-nakliyat-ve-tasimacilik', 'Reşatbey', 'Reşatbey Mah. 62006. Sk. No:15', '0535 691 57 97', NULL, NULL, NULL, 'ChIJ-72yPs6JKBUR529dIosgXJc', 'https://www.google.com/maps/place/?q=place_id:ChIJ-72yPs6JKBUR529dIosgXJc', NULL, NULL, 'Şahin Ekspres Evden Eve Nakliyat ve Taşımacılık, Adana Seyhan ilçesi Reşatbey mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü, Eşya Depolama hizmetleri veriyor.', 4.7, 35, true, false, 2, true),
  (3, 1, 1, 'Adana Şehirler Arası Nakliyat', 'adana-sehirler-arasi-nakliyat', 'Reşatbey', 'Reşatbey Mah. Cumhuriyet Cd. No:33', '0533 144 84 66', NULL, NULL, NULL, 'ChIJa4vFoETJKBURstKVzIak1-o', 'https://www.google.com/maps/place/?q=place_id:ChIJa4vFoETJKBURstKVzIak1-o', NULL, NULL, 'Adana Şehirler Arası Nakliyat, Adana Seyhan ilçesi Reşatbey mahallesinde faaliyet gösteriyor. Şehirler Arası, Parça Eşya hizmetleri veriyor.', NULL, NULL, true, false, 3, true),
  (4, 1, 1, 'Akzaman Uluslararası Nakliyat', 'akzaman-uluslararasi-nakliyat', 'Reşatbey', 'Reşatbey Mah. 62005. Sk. No:24 K:1', '0322 431 07 01', NULL, NULL, NULL, 'ChIJQ7nYI1yPKBURpEoKRquYNv0', 'https://www.google.com/maps/place/?q=place_id:ChIJQ7nYI1yPKBURpEoKRquYNv0', NULL, NULL, 'Akzaman Uluslararası Nakliyat, Adana Seyhan ilçesi Reşatbey mahallesinde faaliyet gösteriyor. Uluslararası, Yurt Dışı Taşıma hizmetleri veriyor.', 5.0, 9, true, false, 4, true),
  (5, 1, 1, 'Adana Evden Eve Nakliyat (Ziyapaşa)', 'adana-evden-eve-nakliyat-ziyapasa', 'Ziyapaşa', 'Ziyapaşa Mah. 67037. Sk. No:5', '0545 457 38 10', NULL, NULL, NULL, 'ChIJ-QrID5GPKBURYa6Zq2e7jx4', 'https://www.google.com/maps/place/?q=place_id:ChIJ-QrID5GPKBURYa6Zq2e7jx4', NULL, NULL, 'Adana Evden Eve Nakliyat (Ziyapaşa), Adana Seyhan ilçesi Ziyapaşa mahallesinde faaliyet gösteriyor. Evden Eve, Şehir İçi hizmetleri veriyor.', NULL, NULL, true, false, 5, true),
  (6, 1, 1, 'Adana Tufan Evden Eve Taşımacılık', 'adana-tufan-evden-eve-tasimacilik', 'Çınarlı', 'Çınarlı Mah. 61027. Sk. No:4/A', '0543 248 96 20', NULL, NULL, NULL, 'ChIJAxibeLSPKBURR2BcSBZkgi8', 'https://www.google.com/maps/place/?q=place_id:ChIJAxibeLSPKBURR2BcSBZkgi8', NULL, NULL, 'Adana Tufan Evden Eve Taşımacılık, Adana Seyhan ilçesi Çınarlı mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü, Şehirler Arası hizmetleri veriyor.', 4.8, 93, true, false, 6, true),
  (7, 1, 1, 'Paçrazlar Evden Eve Nakliyat', 'pacrazlar-evden-eve-nakliyat', 'Dağlıoğlu', 'Dağlıoğlu Mah. 14018. Sk. No:16/B', '0539 242 18 29', NULL, NULL, NULL, 'ChIJ8bPpJRKFKBURYTCY_Agr-Is', 'https://www.google.com/maps/place/?q=place_id:ChIJ8bPpJRKFKBURYTCY_Agr-Is', NULL, NULL, 'Paçrazlar Evden Eve Nakliyat, Adana Seyhan ilçesi Dağlıoğlu mahallesinde faaliyet gösteriyor. Evden Eve, Şehirler Arası hizmetleri veriyor.', 5.0, 5, true, false, 7, true),
  (8, 1, 1, 'Miraç Nakliyat - Adana Evden Eve Taşımacılık', 'mirac-nakliyat-adana-evden-eve-tasimacilik', 'Tellidere', 'Tellidere Mah. 72114. Sk. No:11 Kat:1', '0536 931 70 03', NULL, NULL, NULL, 'ChIJPVyppn2JKBURjiAoJHBenv4', 'https://www.google.com/maps/place/?q=place_id:ChIJPVyppn2JKBURjiAoJHBenv4', NULL, NULL, 'Miraç Nakliyat - Adana Evden Eve Taşımacılık, Adana Seyhan ilçesi Tellidere mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü, Şehirler Arası hizmetleri veriyor.', 4.9, 209, false, false, 8, true),
  (9, 1, 1, 'Adana İnci Evden Eve Nakliyat', 'adana-inci-evden-eve-nakliyat', 'Gürselpaşa', 'Gürselpaşa Mah. 75042. Sk. No:4', '0551 810 19 92', NULL, NULL, NULL, 'ChIJtfHFcWmJKBURp37_fkD-F_w', 'https://www.google.com/maps/place/?q=place_id:ChIJtfHFcWmJKBURp37_fkD-F_w', NULL, NULL, 'Adana İnci Evden Eve Nakliyat, Adana Seyhan ilçesi Gürselpaşa mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü hizmetleri veriyor.', 5.0, 167, false, false, 9, true),
  (10, 1, 1, 'Adana Güzeltaş Evden Eve Nakliyat', 'adana-guzeltas-evden-eve-nakliyat', 'Gülbahçesi', 'Gülbahçesi Mah. 13314. Sk. No:172/A', '0551 351 91 14', NULL, NULL, NULL, 'ChIJTcPp7MeHKBUR0yiIjzDBsOs', 'https://www.google.com/maps/place/?q=place_id:ChIJTcPp7MeHKBUR0yiIjzDBsOs', NULL, NULL, 'Adana Güzeltaş Evden Eve Nakliyat, Adana Seyhan ilçesi Gülbahçesi mahallesinde faaliyet gösteriyor. Evden Eve, Eşya Depolama, Şehirler Arası hizmetleri veriyor.', 5.0, 148, false, false, 10, true),
  (11, 1, 1, 'Adana Aktay Evden Eve Taşımacılık', 'adana-aktay-evden-eve-tasimacilik', 'Fatih', 'Fatih Mah. 73012. Sk. No:2', '0545 675 44 05', NULL, NULL, NULL, 'ChIJobtP6fABwGkRJpPsphxNjdw', 'https://www.google.com/maps/place/?q=place_id:ChIJobtP6fABwGkRJpPsphxNjdw', NULL, NULL, 'Adana Aktay Evden Eve Taşımacılık, Adana Seyhan ilçesi Fatih mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü, Şehirler Arası hizmetleri veriyor.', 5.0, 65, false, false, 11, true),
  (12, 1, 1, 'Adana Onur Evden Eve Nakliyat', 'adana-onur-evden-eve-nakliyat', 'Gürselpaşa', 'Gürselpaşa Mah. 75097. Sk. No:4 D:14', '0537 229 31 02', NULL, NULL, NULL, 'ChIJYygR3IeJKBURllKdTuiAU44', 'https://www.google.com/maps/place/?q=place_id:ChIJYygR3IeJKBURllKdTuiAU44', NULL, NULL, 'Adana Onur Evden Eve Nakliyat, Adana Seyhan ilçesi Gürselpaşa mahallesinde faaliyet gösteriyor. Evden Eve, Şehir İçi hizmetleri veriyor.', 4.9, 118, false, false, 12, true),
  (13, 1, 1, 'Adana Cihan Evden Eve Nakliyat', 'adana-cihan-evden-eve-nakliyat', 'Gürselpaşa', 'Gürselpaşa Mah. 75128. Sk. No:12 D:1', '0537 254 61 43', NULL, NULL, NULL, 'ChIJ5a-NHIGJKBURW0EFpDg8iTw', 'https://www.google.com/maps/place/?q=place_id:ChIJ5a-NHIGJKBURW0EFpDg8iTw', NULL, NULL, 'Adana Cihan Evden Eve Nakliyat, Adana Seyhan ilçesi Gürselpaşa mahallesinde faaliyet gösteriyor. Evden Eve, Şehirler Arası hizmetleri veriyor.', 5.0, 33, false, false, 13, true),
  (14, 1, 1, 'Adana Gündoğdu Evden Eve Nakliyat - Asansörlü Taşımacılık', 'adana-gundogdu-evden-eve-nakliyat-asansorlu-tasimacilik', 'Pınar', 'Pınar Mah. 74054. Sk. No:4 Kat:4', '0534 858 91 88', NULL, NULL, NULL, 'ChIJx2kKnn59KBURNwCmHgjW5NY', 'https://www.google.com/maps/place/?q=place_id:ChIJx2kKnn59KBURNwCmHgjW5NY', NULL, NULL, 'Adana Gündoğdu Evden Eve Nakliyat - Asansörlü Taşımacılık, Adana Seyhan ilçesi Pınar mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü, Şehirler Arası hizmetleri veriyor.', 5.0, 92, false, false, 14, true),
  (15, 1, 1, 'Kanun Nakliyat - Adana Evden Eve', 'kanun-nakliyat-adana-evden-eve', 'Gürselpaşa', 'Gürselpaşa Mah. 75078. Sk. No:2', '0538 410 91 13', NULL, NULL, NULL, 'ChIJp4tBqDIDDgIRf7l4NFrEPEU', 'https://www.google.com/maps/place/?q=place_id:ChIJp4tBqDIDDgIRf7l4NFrEPEU', NULL, NULL, 'Kanun Nakliyat - Adana Evden Eve, Adana Seyhan ilçesi Gürselpaşa mahallesinde faaliyet gösteriyor. Evden Eve, Şehir İçi hizmetleri veriyor.', 4.9, 75, false, false, 15, true),
  (16, 1, 1, 'Adana Ömeroğlu Evden Eve Nakliyat', 'adana-omeroglu-evden-eve-nakliyat', 'Pınar', 'Pınar Mah. 74098. Sk. No:5', '0537 731 80 87', NULL, NULL, NULL, 'ChIJkx0IOX6JKBURWRKb9lb0z7k', 'https://www.google.com/maps/place/?q=place_id:ChIJkx0IOX6JKBURWRKb9lb0z7k', NULL, NULL, 'Adana Ömeroğlu Evden Eve Nakliyat, Adana Seyhan ilçesi Pınar mahallesinde faaliyet gösteriyor. Evden Eve, Şehirler Arası hizmetleri veriyor.', 4.9, 56, false, false, 16, true),
  (17, 1, 1, 'Miran Evden Eve Nakliyat - Asansörlü Taşımacılık', 'miran-evden-eve-nakliyat-asansorlu-tasimacilik', 'Tellidere', 'Tellidere Mah. 72120. Sk. No:18 Kat:3', '0534 204 01 37', NULL, NULL, NULL, 'ChIJFbfHobOJKBURPZ11o0_Y6iI', 'https://www.google.com/maps/place/?q=place_id:ChIJFbfHobOJKBURPZ11o0_Y6iI', NULL, NULL, 'Miran Evden Eve Nakliyat - Asansörlü Taşımacılık, Adana Seyhan ilçesi Tellidere mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü hizmetleri veriyor.', 5.0, 62, false, false, 17, true),
  (18, 1, 1, 'Öz Çukurova Kargo Evden Eve Nakliyat', 'oz-cukurova-kargo-evden-eve-nakliyat', 'Tellidere', 'Tellidere Mah. 72120. Sk. No:10', '0532 551 29 86', NULL, NULL, NULL, 'ChIJebpCYVGJKBURYTyOv_8ieJI', 'https://www.google.com/maps/place/?q=place_id:ChIJebpCYVGJKBURYTyOv_8ieJI', NULL, NULL, 'Öz Çukurova Kargo Evden Eve Nakliyat, Adana Seyhan ilçesi Tellidere mahallesinde faaliyet gösteriyor. Evden Eve, Parça Eşya hizmetleri veriyor.', 5.0, 4, false, false, 18, true),
  (19, 1, 1, 'Adana Evden Eve Nakliye ve Eşya Depolama', 'adana-evden-eve-nakliye-ve-esya-depolama', 'Fatih', 'Fatih Mah. 73158. Sk. No:25/A Kat:Z', '0539 480 34 53', NULL, NULL, NULL, 'ChIJYeIa1v6JKBUR52pvu4N8lVQ', 'https://www.google.com/maps/place/?q=place_id:ChIJYeIa1v6JKBUR52pvu4N8lVQ', NULL, NULL, 'Adana Evden Eve Nakliye ve Eşya Depolama, Adana Seyhan ilçesi Fatih mahallesinde faaliyet gösteriyor. Evden Eve, Eşya Depolama hizmetleri veriyor.', 5.0, 5, false, false, 19, true),
  (20, 1, 1, 'Adana Enfal 17 Evden Eve Taşımacılık', 'adana-enfal-17-evden-eve-tasimacilik', 'Tellidere', 'Tellidere Mah. 72119. Sk. No:10', '0536 780 28 38', NULL, NULL, NULL, 'ChIJC5mM2pR9KBURM1ZKBNf80uw', 'https://www.google.com/maps/place/?q=place_id:ChIJC5mM2pR9KBURM1ZKBNf80uw', NULL, NULL, 'Adana Enfal 17 Evden Eve Taşımacılık, Adana Seyhan ilçesi Tellidere mahallesinde faaliyet gösteriyor. Evden Eve, Şehirler Arası hizmetleri veriyor.', 5.0, 54, false, false, 20, true),
  (21, 1, 1, 'Başak Evden Eve Nakliyat ve Asansörlü Şehir İçi Taşımacılık', 'basak-evden-eve-nakliyat-ve-asansorlu-sehir-ici-tasimacilik', 'Tellidere', 'Tellidere Mah. 72119. Sk. No:16/2', '0537 702 01 13', NULL, NULL, NULL, 'ChIJjW444mqJKBURv4VJN-5azbo', 'https://www.google.com/maps/place/?q=place_id:ChIJjW444mqJKBURv4VJN-5azbo', NULL, NULL, 'Başak Evden Eve Nakliyat ve Asansörlü Şehir İçi Taşımacılık, Adana Seyhan ilçesi Tellidere mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü, Şehir İçi hizmetleri veriyor.', 5.0, 45, false, false, 21, true),
  (22, 1, 1, 'Adana Çağrı Nakliyat Evden Eve Taşımacılık', 'adana-cagri-nakliyat-evden-eve-tasimacilik', 'Gürselpaşa', 'Gürselpaşa Mah. 75068. Sk. No:2 Kat:2', '0534 961 45 75', NULL, NULL, NULL, 'ChIJfcLuAbOJKBUReP4RoGh3Zns', 'https://www.google.com/maps/place/?q=place_id:ChIJfcLuAbOJKBUReP4RoGh3Zns', NULL, NULL, 'Adana Çağrı Nakliyat Evden Eve Taşımacılık, Adana Seyhan ilçesi Gürselpaşa mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü, Şehirler Arası hizmetleri veriyor.', 4.9, 59, false, false, 22, true),
  (23, 1, 1, 'Adana Asansör Taşıma', 'adana-asansor-tasima', 'Bahçeşehir', 'Bahçeşehir Mah. 86041. Sk. No:26/B', '0505 177 40 97', NULL, NULL, NULL, 'ChIJF0ULPFaJKBURDWJclrZyGQg', 'https://www.google.com/maps/place/?q=place_id:ChIJF0ULPFaJKBURDWJclrZyGQg', NULL, NULL, 'Adana Asansör Taşıma, Adana Seyhan ilçesi Bahçeşehir mahallesinde faaliyet gösteriyor. Asansörlü, Asansör Kiralama hizmetleri veriyor.', 5.0, 1, false, false, 23, true),
  (24, 1, 2, 'Adana Kiralık Asansör', 'adana-kiralik-asansor', 'Yurt', 'Yurt Mah. 71411. Sk. No:11', '0533 085 91 94', NULL, NULL, NULL, 'ChIJ63mI3eiJKBURoGAtEmyPuI8', 'https://www.google.com/maps/place/?q=place_id:ChIJ63mI3eiJKBURoGAtEmyPuI8', NULL, NULL, 'Adana Kiralık Asansör, Adana Çukurova ilçesi Yurt mahallesinde faaliyet gösteriyor. Asansör Kiralama, Asansörlü hizmetleri veriyor.', 5.0, 5, false, false, 24, true),
  (25, 1, 2, 'Movira Evden Eve Nakliyat - Asansörlü Taşımacılık', 'movira-evden-eve-nakliyat-asansorlu-tasimacilik', 'Huzurevleri', 'Huzurevleri Mah. Turgut Özal Blv. Anadolu Lisesi Cd. yanı', '0533 160 87 11', NULL, NULL, NULL, 'ChIJMS-zyAWJKBUR5VD2_iPi-q0', 'https://www.google.com/maps/place/?q=place_id:ChIJMS-zyAWJKBUR5VD2_iPi-q0', NULL, NULL, 'Movira Evden Eve Nakliyat - Asansörlü Taşımacılık, Adana Çukurova ilçesi Huzurevleri mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü hizmetleri veriyor.', 5.0, 2, false, false, 25, true),
  (26, 1, 2, 'Adana Ova-Taş Evden Eve Nakliyat', 'adana-ova-tas-evden-eve-nakliyat', 'Toros', 'Toros Mah. Şht. Ebubekir Durmuş Sk. Kibritoğlu Apt.', '0555 102 18 10', NULL, NULL, NULL, 'ChIJd_iZ0L2JKBURd8_S-RFBx8w', 'https://www.google.com/maps/place/?q=place_id:ChIJd_iZ0L2JKBURd8_S-RFBx8w', NULL, NULL, 'Adana Ova-Taş Evden Eve Nakliyat, Adana Çukurova ilçesi Toros mahallesinde faaliyet gösteriyor. Evden Eve, Şehir İçi hizmetleri veriyor.', 5.0, 24, false, false, 26, true),
  (27, 1, 2, 'Adana Öz Çayır Evden Eve Nakliyat', 'adana-oz-cayir-evden-eve-nakliyat', 'Toros', 'Toros Mah. 1. Sk. No:9/A', '0322 226 82 84', NULL, NULL, NULL, 'ChIJd1PnJPCJKBURj-0i0hffR8M', 'https://www.google.com/maps/place/?q=place_id:ChIJd1PnJPCJKBURj-0i0hffR8M', NULL, NULL, 'Adana Öz Çayır Evden Eve Nakliyat, Adana Çukurova ilçesi Toros mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü hizmetleri veriyor.', 5.0, 1, false, false, 27, true),
  (28, 1, 2, 'Adana Şahin Evden Eve Taşımacılık', 'adana-sahin-evden-eve-tasimacilik', 'Huzurevleri', 'Huzurevleri Mah. Alparslan Türkeş Blv. No:309/B', '0534 513 09 12', NULL, NULL, NULL, 'ChIJO1k8rbeJKBURGxZx1g9RDTY', 'https://www.google.com/maps/place/?q=place_id:ChIJO1k8rbeJKBURGxZx1g9RDTY', NULL, NULL, 'Adana Şahin Evden Eve Taşımacılık, Adana Çukurova ilçesi Huzurevleri mahallesinde faaliyet gösteriyor. Evden Eve, Şehir İçi hizmetleri veriyor.', 5.0, 3, false, false, 28, true),
  (29, 1, 2, 'Adana Asansör Kiralama', 'adana-asansor-kiralama', 'Yüzüncüyıl', 'Yüzüncüyıl Mah. 85105. Sk. No:4', '0322 409 51 93', NULL, NULL, NULL, 'ChIJu71whoCJKBURO_v6DLKS6z4', 'https://www.google.com/maps/place/?q=place_id:ChIJu71whoCJKBURO_v6DLKS6z4', NULL, NULL, 'Adana Asansör Kiralama, Adana Çukurova ilçesi Yüzüncüyıl mahallesinde faaliyet gösteriyor. Asansör Kiralama, Asansörlü hizmetleri veriyor.', 5.0, 26, false, false, 29, true),
  (30, 1, 3, 'Yıldırım Taşımacılık - Evden Eve Asansörlü Taşıma', 'yildirim-tasimacilik-evden-eve-asansorlu-tasima', 'Kışla', 'Kışla Mah. 4455. Sk. No:25', '0544 424 30 30', NULL, NULL, NULL, 'ChIJx-RgL0cyMIcRV7lGNDkScqc', 'https://www.google.com/maps/place/?q=place_id:ChIJx-RgL0cyMIcRV7lGNDkScqc', NULL, NULL, 'Yıldırım Taşımacılık - Evden Eve Asansörlü Taşıma, Adana Yüreğir ilçesi Kışla mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü, Eşya Depolama hizmetleri veriyor.', 5.0, 5, false, false, 30, true),
  (31, 1, 3, 'Yarenler Evden Eve Nakliyat', 'yarenler-evden-eve-nakliyat', 'Atakent', 'Atakent Mah. 2269. Sk. No:27', '0553 640 22 91', NULL, NULL, NULL, 'ChIJYcClF4uPKBURM_y18QAMiXM', 'https://www.google.com/maps/place/?q=place_id:ChIJYcClF4uPKBURM_y18QAMiXM', NULL, NULL, 'Yarenler Evden Eve Nakliyat, Adana Yüreğir ilçesi Atakent mahallesinde faaliyet gösteriyor. Evden Eve, Şehir İçi hizmetleri veriyor.', 4.4, 7, false, false, 31, true),
  (32, 1, 3, 'Sarıçam Evden Eve Nakliyat', 'saricam-evden-eve-nakliyat', 'Sarıçam', 'Sarıçam Mah. 2461. Sk. No:8', '0545 457 38 10', NULL, NULL, NULL, 'ChIJ74VPZrqPKBURohKj3Hnp3vc', 'https://www.google.com/maps/place/?q=place_id:ChIJ74VPZrqPKBURohKj3Hnp3vc', NULL, NULL, 'Sarıçam Evden Eve Nakliyat, Adana Yüreğir ilçesi Sarıçam mahallesinde faaliyet gösteriyor. Evden Eve, Şehir İçi hizmetleri veriyor.', NULL, NULL, false, false, 32, true),
  (33, 1, 4, 'Adana Evden Eve Nakliyat - My Global', 'adana-evden-eve-nakliyat-my-global', 'Ertuğrulgazi', 'Ertuğrulgazi Mah. Akkuyu 18025. Sk. No:5', '0543 589 69 59', NULL, NULL, NULL, 'ChIJjY7z7oCTKBURHL2f5E_YmPY', 'https://www.google.com/maps/place/?q=place_id:ChIJjY7z7oCTKBURHL2f5E_YmPY', NULL, NULL, 'Adana Evden Eve Nakliyat - My Global, Adana Sarıçam ilçesi Ertuğrulgazi mahallesinde faaliyet gösteriyor. Evden Eve, Şehirler Arası hizmetleri veriyor.', 4.9, 38, false, false, 33, true),
  (34, 1, 4, 'Adana Büyükün Nakliyat', 'adana-buyukun-nakliyat', 'Şahintepe', 'Şahintepe Mah. 3153. Sk. No:4', '0533 337 39 52', NULL, NULL, NULL, 'ChIJQx9Zc1STKBURVU2E0_jwxFk', 'https://www.google.com/maps/place/?q=place_id:ChIJQx9Zc1STKBURVU2E0_jwxFk', NULL, NULL, 'Adana Büyükün Nakliyat, Adana Sarıçam ilçesi Şahintepe mahallesinde faaliyet gösteriyor. Evden Eve, Şehir İçi hizmetleri veriyor.', 5.0, 8, false, false, 34, true),
  (35, 1, 4, 'Hazan Evden Eve Nakliyat', 'hazan-evden-eve-nakliyat', 'Mehmet Akif Ersoy', 'Mehmet Akif Ersoy Mah. 3300. Sk. No:24', '0507 420 41 86', NULL, NULL, NULL, 'ChIJ39jywsORKBUR-58kl6zSBYI', 'https://www.google.com/maps/place/?q=place_id:ChIJ39jywsORKBUR-58kl6zSBYI', NULL, NULL, 'Hazan Evden Eve Nakliyat, Adana Sarıçam ilçesi Mehmet Akif Ersoy mahallesinde faaliyet gösteriyor. Evden Eve hizmetleri veriyor.', 5.0, 1, false, false, 35, true),
  (36, 1, 4, 'Duruş Evden Eve Nakliyat', 'durus-evden-eve-nakliyat', 'Mehmet Akif Ersoy', 'Mehmet Akif Ersoy Mah. 140. Sk. No:16', '0551 595 98 13', NULL, NULL, NULL, 'ChIJfzs-SiWRKBURvWLc40HYwzk', 'https://www.google.com/maps/place/?q=place_id:ChIJfzs-SiWRKBURvWLc40HYwzk', NULL, NULL, 'Duruş Evden Eve Nakliyat, Adana Sarıçam ilçesi Mehmet Akif Ersoy mahallesinde faaliyet gösteriyor. Evden Eve hizmetleri veriyor.', NULL, NULL, false, false, 36, true),
  (37, 1, 4, 'Sarıçam Nakliyat', 'saricam-nakliyat', 'Gültepe', 'Gültepe Mah. 231. Sk. No:36', '0537 409 24 07', NULL, NULL, NULL, 'ChIJjbyzEgeTKBURfeF7-ANDLms', 'https://www.google.com/maps/place/?q=place_id:ChIJjbyzEgeTKBURfeF7-ANDLms', NULL, NULL, 'Sarıçam Nakliyat, Adana Sarıçam ilçesi Gültepe mahallesinde faaliyet gösteriyor. Evden Eve, Parça Eşya hizmetleri veriyor.', 5.0, 1, false, false, 37, true),
  (38, 1, 1, 'Tedbir Evden Eve Nakliyat - Şehirler Arası Taşımacılık', 'tedbir-evden-eve-nakliyat-sehirler-arasi-tasimacilik', 'Fatih', 'Fatih Mah. 73026. Sk. No:32', '0533 575 43 83', NULL, NULL, NULL, 'ChIJ0RvXbhN9KBURqfuRVoFBZDY', 'https://www.google.com/maps/place/?q=place_id:ChIJ0RvXbhN9KBURqfuRVoFBZDY', NULL, NULL, 'Tedbir Evden Eve Nakliyat - Şehirler Arası Taşımacılık, Adana Seyhan ilçesi Fatih mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü, Şehirler Arası hizmetleri veriyor.', 4.6, 319, false, false, 38, true),
  (39, 1, 1, 'Adana Toros Evden Eve Nakliyat', 'adana-toros-evden-eve-nakliyat', 'Fatih', 'Fatih Mah. 73246. Sk. Zemin Kat', '0536 225 93 28', NULL, NULL, NULL, 'ChIJ9VsYEJGJKBURSvVWRvG6118', 'https://www.google.com/maps/place/?q=place_id:ChIJ9VsYEJGJKBURSvVWRvG6118', NULL, NULL, 'Adana Toros Evden Eve Nakliyat, Adana Seyhan ilçesi Fatih mahallesinde faaliyet gösteriyor. Evden Eve, Şehir İçi hizmetleri veriyor.', 5.0, 59, false, false, 39, true),
  (40, 1, 1, 'Erdinç Nakliyat - Adana Evden Eve Taşımacılık', 'erdinc-nakliyat-adana-evden-eve-tasimacilik', 'Pınar', 'Pınar Mah. 74052. Sk. No:1 Kat:4', '0551 688 51 64', NULL, NULL, NULL, 'ChIJRSQsli3lUkMRYdFGOI2gPyc', 'https://www.google.com/maps/place/?q=place_id:ChIJRSQsli3lUkMRYdFGOI2gPyc', NULL, NULL, 'Erdinç Nakliyat - Adana Evden Eve Taşımacılık, Adana Seyhan ilçesi Pınar mahallesinde faaliyet gösteriyor. Evden Eve, Şehirler Arası hizmetleri veriyor.', 5.0, 7, false, false, 40, true),
  (41, 1, 5, 'Ceyhan Gökberk Nakliyat', 'ceyhan-gokberk-nakliyat', 'Namık Kemal', 'Namık Kemal Mah. Ahmet Ural Sk. No:15', '0539 258 93 48', NULL, NULL, NULL, 'ChIJ89AJYm_JKBURUvuFSPjOwYw', 'https://www.google.com/maps/place/?q=place_id:ChIJ89AJYm_JKBURUvuFSPjOwYw', NULL, NULL, 'Ceyhan Gökberk Nakliyat, Adana Ceyhan ilçesi Namık Kemal mahallesinde faaliyet gösteriyor. Evden Eve, Şehirler Arası hizmetleri veriyor.', 5.0, 35, false, false, 41, true),
  (42, 1, 5, 'Asya Nakliyat Ceyhan', 'asya-nakliyat-ceyhan', 'Burhaniye', 'Burhaniye Mah. İnönü Bulvarı 170. Sk. No:21', '0543 501 75 19', NULL, NULL, NULL, 'ChIJoVndtR_JKBURetSN5BELzzo', 'https://www.google.com/maps/place/?q=place_id:ChIJoVndtR_JKBURetSN5BELzzo', NULL, NULL, 'Asya Nakliyat Ceyhan, Adana Ceyhan ilçesi Burhaniye mahallesinde faaliyet gösteriyor. Evden Eve, Şehirler Arası, Parça Eşya hizmetleri veriyor.', 5.0, 56, false, false, 42, true),
  (43, 1, 5, 'Akdoğan Evden Eve Taşımacılık', 'akdogan-evden-eve-tasimacilik', 'Namık Kemal', 'Namık Kemal Mah. Şehitler Bulvarı No:7', '0533 658 30 33', NULL, NULL, NULL, 'ChIJNxDNHcjJKBURCBLS69ZCLsw', 'https://www.google.com/maps/place/?q=place_id:ChIJNxDNHcjJKBURCBLS69ZCLsw', NULL, NULL, 'Akdoğan Evden Eve Taşımacılık, Adana Ceyhan ilçesi Namık Kemal mahallesinde faaliyet gösteriyor. Evden Eve, Şehir İçi hizmetleri veriyor.', 4.2, 46, false, false, 43, true),
  (44, 1, 5, 'Adıgüzel Taşımacılık Ceyhan', 'adiguzel-tasimacilik-ceyhan', 'İstiklal', 'İstiklal Mah. Ahmet Kabaklı Cd. No:94', '0551 076 96 32', NULL, NULL, NULL, 'ChIJ8XpEDQDLKBURsBvjpr9pgYw', 'https://www.google.com/maps/place/?q=place_id:ChIJ8XpEDQDLKBURsBvjpr9pgYw', NULL, NULL, 'Adıgüzel Taşımacılık Ceyhan, Adana Ceyhan ilçesi İstiklal mahallesinde faaliyet gösteriyor. Evden Eve, Şehirler Arası hizmetleri veriyor.', 5.0, 4, false, false, 44, true),
  (45, 1, 5, 'Ceyhan Uğur Şark Nakliyat Lojistik', 'ceyhan-ugur-sark-nakliyat-lojistik', 'Atatürk', 'Atatürk Mah. Adana Cd. No:16 Z-3', '0532 226 88 85', NULL, NULL, NULL, 'ChIJ5c9dMUHJKBURVQH2gerDa28', 'https://www.google.com/maps/place/?q=place_id:ChIJ5c9dMUHJKBURVQH2gerDa28', NULL, NULL, 'Ceyhan Uğur Şark Nakliyat Lojistik, Adana Ceyhan ilçesi Atatürk mahallesinde faaliyet gösteriyor. Lojistik, Şehirler Arası hizmetleri veriyor.', 5.0, 2, false, false, 45, true),
  (46, 1, 5, 'Ceyhan Altın Arı Nakliyat ve Vinç', 'ceyhan-altin-ari-nakliyat-ve-vinc', 'Ulus', 'Ulus Mah. Ömer Özge Sk. No:8', '0532 606 04 01', NULL, NULL, NULL, 'ChIJ4SQzNMPJKBURma9ZAn5XNNs', 'https://www.google.com/maps/place/?q=place_id:ChIJ4SQzNMPJKBURma9ZAn5XNNs', NULL, NULL, 'Ceyhan Altın Arı Nakliyat ve Vinç, Adana Ceyhan ilçesi Ulus mahallesinde faaliyet gösteriyor. Evden Eve, Vinç Hizmeti hizmetleri veriyor.', 5.0, 1, false, false, 46, true),
  (47, 1, 6, 'Kozan Hat Taşımacılık', 'kozan-hat-tasimacilik', 'Tufanpaşa', 'Tufanpaşa Mah. Ladin Sk. No:21/C', '0507 316 53 78', NULL, NULL, NULL, 'ChIJe0EoP_YxKRUR3J6kjGjPpv0', 'https://www.google.com/maps/place/?q=place_id:ChIJe0EoP_YxKRUR3J6kjGjPpv0', NULL, NULL, 'Kozan Hat Taşımacılık, Adana Kozan ilçesi Tufanpaşa mahallesinde faaliyet gösteriyor. Evden Eve, Asansörlü hizmetleri veriyor.', 5.0, 9, false, false, 47, true),
  (48, 1, 6, 'Kozan Evden Eve Taşımacılık', 'kozan-evden-eve-tasimacilik', 'Türkeli', 'Türkeli Mah. Saimbeyli Cd. No:261', '0505 843 17 79', NULL, NULL, NULL, 'ChIJc8iPnesxKRURQuOCuH1ihzk', 'https://www.google.com/maps/place/?q=place_id:ChIJc8iPnesxKRURQuOCuH1ihzk', NULL, NULL, 'Kozan Evden Eve Taşımacılık, Adana Kozan ilçesi Türkeli mahallesinde faaliyet gösteriyor. Evden Eve, Şehir İçi hizmetleri veriyor.', 5.0, 14, false, false, 48, true),
  (49, 1, 6, 'Kozan Zirve Taşımacılık', 'kozan-zirve-tasimacilik', 'Şevkiye', 'Şevkiye Mah. 1121. Sokak', '0543 922 45 78', NULL, NULL, NULL, 'ChIJ_RxizBBPdiQR6i_LYMmniEs', 'https://www.google.com/maps/place/?q=place_id:ChIJ_RxizBBPdiQR6i_LYMmniEs', NULL, NULL, 'Kozan Zirve Taşımacılık, Adana Kozan ilçesi Şevkiye mahallesinde faaliyet gösteriyor. Evden Eve, Şehirler Arası hizmetleri veriyor.', 5.0, 10, false, false, 49, true),
  (50, 1, 6, 'Kozan Hedef Taşımacılık', 'kozan-hedef-tasimacilik', 'Tufanpaşa', 'Tufanpaşa Mah. Çelikler Sk. No:14 D:9/C', '0543 915 33 34', NULL, NULL, NULL, 'ChIJYWQ52m8xKRURw72du9Kk_Aw', 'https://www.google.com/maps/place/?q=place_id:ChIJYWQ52m8xKRURw72du9Kk_Aw', NULL, NULL, 'Kozan Hedef Taşımacılık, Adana Kozan ilçesi Tufanpaşa mahallesinde faaliyet gösteriyor. Evden Eve, Şehir İçi hizmetleri veriyor.', 4.0, 30, false, false, 50, true),
  (51, 1, 7, 'M. Yastıkülah Lojistik', 'm-yastikulah-lojistik', 'Karapınar', 'Karapınar Mah. Kuvayi Milliye Cd. No:34', '0507 406 59 28', NULL, NULL, NULL, 'ChIJiVPZYh1dKBURYTLNd56EcKE', 'https://www.google.com/maps/place/?q=place_id:ChIJiVPZYh1dKBURYTLNd56EcKE', NULL, NULL, 'M. Yastıkülah Lojistik, Adana Karaisalı ilçesi Karapınar mahallesinde faaliyet gösteriyor. Lojistik, Şehirler Arası hizmetleri veriyor.', NULL, NULL, false, false, 51, true)
on conflict (id) do nothing;

insert into firma_kategori (firma_id, kategori_id) values
  (1, 1),
  (1, 3),
  (10, 1),
  (10, 3),
  (10, 5),
  (11, 1),
  (11, 2),
  (11, 3),
  (12, 1),
  (12, 4),
  (13, 1),
  (13, 3),
  (14, 1),
  (14, 2),
  (14, 3),
  (15, 1),
  (15, 4),
  (16, 1),
  (16, 3),
  (17, 1),
  (17, 2),
  (18, 1),
  (18, 6),
  (19, 1),
  (19, 5),
  (2, 1),
  (2, 2),
  (2, 5),
  (20, 1),
  (20, 3),
  (21, 1),
  (21, 2),
  (21, 4),
  (22, 1),
  (22, 2),
  (22, 3),
  (23, 2),
  (23, 7),
  (24, 2),
  (24, 7),
  (25, 1),
  (25, 2),
  (26, 1),
  (26, 4),
  (27, 1),
  (27, 2),
  (28, 1),
  (28, 4),
  (29, 2),
  (29, 7),
  (3, 3),
  (3, 6),
  (30, 1),
  (30, 2),
  (30, 5),
  (31, 1),
  (31, 4),
  (32, 1),
  (32, 4),
  (33, 1),
  (33, 3),
  (34, 1),
  (34, 4),
  (35, 1),
  (36, 1),
  (37, 1),
  (37, 6),
  (38, 1),
  (38, 2),
  (38, 3),
  (39, 1),
  (39, 4),
  (4, 8),
  (40, 1),
  (40, 3),
  (41, 1),
  (41, 3),
  (42, 1),
  (42, 3),
  (42, 6),
  (43, 1),
  (43, 4),
  (44, 1),
  (44, 3),
  (45, 3),
  (45, 9),
  (46, 1),
  (46, 10),
  (47, 1),
  (47, 2),
  (48, 1),
  (48, 4),
  (49, 1),
  (49, 3),
  (5, 1),
  (5, 4),
  (50, 1),
  (50, 4),
  (51, 3),
  (51, 9),
  (6, 1),
  (6, 2),
  (6, 3),
  (7, 1),
  (7, 3),
  (8, 1),
  (8, 2),
  (8, 3),
  (9, 1),
  (9, 2)
on conflict (firma_id, kategori_id) do nothing;

insert into sss (kapsam, kapsam_id, soru, cevap, sira, aktif) values
  ('genel', NULL, 'Adana''da evden eve nakliyat ne kadar tutar?', 'Fiyat; ev tipi, kat durumu, asansör ihtiyacı ve mesafeye göre değişir. Net rakam için formu doldurup birden fazla firmadan teklif almanız en sağlıklısıdır.', 1, true),
  ('genel', NULL, 'Dış cephe asansörü ne zaman gerekir?', 'Bina asansörü dar olduğunda, koltuk ve dolap gibi büyük parçalar sığmadığında ya da 3. kattan yukarısında yaşıyorsanız dış cephe asansörü kullanılır.', 2, true),
  ('genel', NULL, 'Teklif almak ücretli mi?', 'Hayır. Rehber üzerinden teklif istemek tamamen ücretsizdir ve hiçbir taahhüt altına girmezsiniz.', 3, true),
  ('genel', NULL, 'Eşyalarım kaç günde taşınır?', 'Adana içi standart bir ev taşıması genellikle aynı gün tamamlanır. Şehirler arası taşımalarda mesafeye göre 1-3 gün sürer.', 4, true),
  ('genel', NULL, 'Ambalaj malzemesi fiyata dahil mi?', 'Firmadan firmaya değişiyor. Bazı firmalar koli, streç film ve balonlu naylonu pakete dahil ederken bazıları ayrı fatura ediyor.', 5, true),
  ('genel', NULL, 'Firmam bu listede yok, nasıl eklenir?', 'Firma Ekle sayfasındaki formu doldurmanız yeterli. Bilgileriniz kontrol edildikten sonra yayınlanır.', 6, true);

insert into ayarlar (anahtar, deger) values
  ('site_adi', 'Adana Nakliyat Rehberi'),
  ('domain', 'https://adanatasimasirketleri.com.tr'),
  ('mail', 'agenli86@gmail.com'),
  ('varsayilan_il', 'adana'),
  ('baraj_aktif', '1'),
  ('baraj_ad', 'Baraj Asansörlü Taşımacılık'),
  ('baraj_alt', 'Adana geneli asansörlü evden eve nakliyat ve şehir içi taşıma — 7/24 hizmet'),
  ('baraj_site', 'https://barajasansorlutasimacilik.com.tr/'),
  ('baraj_harita', 'https://maps.app.goo.gl/GGAYX2uYGeLqDxz46')
on conflict (anahtar) do update set deger = excluded.deger;

-- serial sequence'leri son id'ye hizala
select setval(pg_get_serial_sequence('iller','id'), coalesce((select max(id) from iller), 1), true);
select setval(pg_get_serial_sequence('ilceler','id'), coalesce((select max(id) from ilceler), 1), true);
select setval(pg_get_serial_sequence('kategoriler','id'), coalesce((select max(id) from kategoriler), 1), true);
select setval(pg_get_serial_sequence('firmalar','id'), coalesce((select max(id) from firmalar), 1), true);
select setval(pg_get_serial_sequence('sss','id'), coalesce((select max(id) from sss), 1), true);
select setval(pg_get_serial_sequence('galeri','id'), coalesce((select max(id) from galeri), 1), true);
select setval(pg_get_serial_sequence('yorumlar','id'), coalesce((select max(id) from yorumlar), 1), true);
select setval(pg_get_serial_sequence('basvurular','id'), coalesce((select max(id) from basvurular), 1), true);
select setval(pg_get_serial_sequence('bannerlar','id'), coalesce((select max(id) from bannerlar), 1), true);
select setval(pg_get_serial_sequence('sayfalar','id'), coalesce((select max(id) from sayfalar), 1), true);
select setval(pg_get_serial_sequence('blog_kategori','id'), coalesce((select max(id) from blog_kategori), 1), true);
select setval(pg_get_serial_sequence('blog_yazi','id'), coalesce((select max(id) from blog_yazi), 1), true);
select setval(pg_get_serial_sequence('blog_etiket','id'), coalesce((select max(id) from blog_etiket), 1), true);
